import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface BriefItem {
  id: string;
  title: string;
  source: string;
  url: string;
  publishedAt: string;
  tag: "Tech" | "Policy" | "Research" | "Industry" | "Risk";
  summary: string;
  impact: string;
}

interface ExecutiveBrief {
  generatedAt: string;
  timeRange: string;
  items: BriefItem[];
  rejectedCount: number;
  sourcesUsed: string[];
}

// Generate simple HTML that can be converted to PDF
function generatePDFHTML(brief: ExecutiveBrief): string {
  const formatDate = (dateStr: string) => {
    try {
      return new Date(dateStr).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    } catch {
      return dateStr;
    }
  };

  const itemsHTML = brief.items.map((item, index) => `
    <div style="margin-bottom: 24px; padding-bottom: 24px; border-bottom: 1px solid #e5e5e5;">
      <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
        <span style="background: ${getTagColor(item.tag)}; color: white; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600;">${item.tag}</span>
        <span style="color: #666; font-size: 12px;">${item.source} · ${formatDate(item.publishedAt)}</span>
      </div>
      <h3 style="margin: 0 0 8px 0; font-size: 16px; font-weight: 600; color: #111;">${index + 1}. ${item.title}</h3>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #333; line-height: 1.5;">${item.summary}</p>
      <p style="margin: 0; font-size: 13px; color: #666; font-style: italic;">Why it matters: ${item.impact}</p>
    </div>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Executive Brief - ${brief.timeRange}</title>
  <style>
    @page {
      margin: 1in;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #111;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 24px;
      border-bottom: 2px solid #111;
    }
    .header h1 {
      margin: 0 0 8px 0;
      font-size: 28px;
      font-weight: 700;
    }
    .header p {
      margin: 0;
      color: #666;
      font-size: 14px;
    }
    .meta {
      display: flex;
      justify-content: space-between;
      margin-bottom: 32px;
      padding: 16px;
      background: #f9f9f9;
      border-radius: 8px;
      font-size: 13px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 24px;
      border-top: 1px solid #e5e5e5;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Executive AI Brief</h1>
    <p>This Week in AI, Simplified for Leaders</p>
  </div>
  
  <div class="meta">
    <span><strong>Period:</strong> ${brief.timeRange}</span>
    <span><strong>Generated:</strong> ${formatDate(brief.generatedAt)}</span>
    <span><strong>Articles:</strong> ${brief.items.length}</span>
  </div>
  
  ${itemsHTML}
  
  <div class="footer">
    <p>Generated by Oxford Intelligence</p>
    <p>Sources: ${brief.sourcesUsed.slice(0, 5).join(', ')}${brief.sourcesUsed.length > 5 ? ` and ${brief.sourcesUsed.length - 5} more` : ''}</p>
  </div>
</body>
</html>
  `;
}

function getTagColor(tag: string): string {
  switch (tag) {
    case "Tech": return "#0066cc";
    case "Policy": return "#7c3aed";
    case "Research": return "#059669";
    case "Industry": return "#d97706";
    case "Risk": return "#dc2626";
    default: return "#6b7280";
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { brief } = await req.json() as { brief: ExecutiveBrief };
    
    if (!brief || !brief.items) {
      throw new Error("Invalid brief data");
    }
    
    const html = generatePDFHTML(brief);
    
    return new Response(html, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="ai_research_and_news_${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
    
  } catch (error) {
    console.error("PDF generation error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
